jobs:
  - job: testpostgrestcp31
    displayName: "PostgreSQL .Net Core 3.1"

    pool:
      vmImage: "ubuntu-latest"

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x
          
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true  
                    
      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: docker run --name postgres -e POSTGRES_PASSWORD=Password12! -p 5432:5432 -d postgres:latest
        displayName: "Run PostgreSQL on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests2.PostgresTcp -f netcoreapp3.1 --logger trx
        name: postgrestcptests
        displayName: "PostgreSQL Tcp Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"


      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testpostgrestcp7
    displayName: "PostgreSQL .Net 7"

    pool:
      vmImage: "ubuntu-latest"

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true          
          
      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: docker run --name postgres -e POSTGRES_PASSWORD=Password12! -p 5432:5432 -d postgres:latest
        displayName: "Run PostgreSQL on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests2.PostgresTcp -f net7.0 --logger trx
        name: postgrestcptests
        displayName: "PostgreSQL Tcp Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

 