jobs:

  - job: testbasics
    displayName: "Tests Basics"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"
      AZUREDEV: "true"

    steps:

      - script: printenv
        displayName: Get env variables

      # Use the latest .NET SDK
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true

      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.StandAlone -f net6.0 --logger trx
        name: standalonetests
        displayName: "Standalone Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.UnitTests -f net6.0 --logger trx
        name: unittests
        displayName: "Unit Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlservertcp7
    displayName: "Sql TCP .Net 7"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true          
          
      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerTcp -f net7.0 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Tcp Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlservertcp6
    displayName: "Sql TCP .Net 6"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true          
          
      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerTcp -f net6.0 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Tcp Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlservertcp31
    displayName: "Sql TCP .Net Core 3.1"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true
          
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true   

      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerTcp -f netcoreapp3.1 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Tcp Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlserverhttp6
    displayName: "Sql HTTP .Net 6"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:

      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true
          
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true   

      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerHttp  -f net6.0 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Http Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlserverhttp31
    displayName: "Sql HTTP .Net Core 3.1"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true
          
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true   

      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerHttp -f netcoreapp3.1 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Http Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlserverct31
    displayName: "Sql CT .Net Core 3.1"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true
          
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true   

      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerChangeTracking -f netcoreapp3.1 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Change Tracking Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"

  - job: testssqlserverct6
    displayName: "Sql CT .Net 6"

    pool:
      # get an Ubuntu image to be able to get the light SQL container
      vmImage: "ubuntu-latest" # "Ubuntu 16.04" # "ubuntu-latest" # 'VS2017-Win2016'

    variables:
      solution: "**/*.sln"
      buildPlatform: "Any CPU"
      buildConfiguration: "Release"

    steps:

      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true
          
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true   
          
      - script: docker run --name sqlserver -e ACCEPT_EULA=Y -e SA_PASSWORD=Password12! -p 1433:1433 -d mcr.microsoft.com/mssql/server
        displayName: "Run SQL Server latest on Linux container"
 
        # Seems the 3306 is already in use on the machine used by Azure Devops, so redirect to 3307
      - script: docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
        displayName: "Run MySql on Linux container"

      - script: docker run --name mariadb -e MYSQL_ROOT_PASSWORD=Password12! -p 3308:3306 -d mariadb:latest
        displayName: "Run MariaDB on Linux container"

      - script: dotnet test Tests/Dotmim.Sync.Tests/Dotmim.Sync.Tests.csproj --filter Dotmim.Sync.Tests.IntegrationTests.SqlServerChangeTracking -f net6.0 --logger trx
        name: sqlservertcptests
        displayName: "SQL Server Change Tracking Integration Tests"
        continueOnError: true
        env:
          "AZUREDEV": "true"

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"


    displayName: "Release Nuget Packages"

    # dependsOn: Tests
    # condition: succeeded('Tests')

    # Pool on a VS 2017 image to be able to compile for .Net 4.6
    pool:
      vmImage: "ubuntu-latest"

    variables:
      buildConfiguration: "Release"
      artifactName: "release"

    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: 3.x

      # Use the latest .NET SDK
      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 6.x'
        inputs:
          packageType: 'sdk'
          version: 6.0.x
          includePreviewVersions: true

      - task: UseDotNet@2
        displayName: 'Use .Net Sdk 7.x'
        inputs:
          packageType: 'sdk'
          version: 7.0.x
          includePreviewVersions: true

      - script: |
          dotnet build Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Core/Dotmim.Sync.Core.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Core
        displayName: "release nuget Dotmim.Sync.Core"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj -c $(buildConfiguration)  
          dotnet pack Projects/Dotmim.Sync.SqlServer/Dotmim.Sync.SqlServer.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.SqlServer   
        displayName: "release nuget Dotmim.Sync.SqlServer"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.SqlServer.ChangeTracking/Dotmim.Sync.SqlServer.ChangeTracking.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.SqlServer.ChangeTracking/Dotmim.Sync.SqlServer.ChangeTracking.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.SqlServerChangeTracking   
        displayName: "release nuget Dotmim.Sync.SqlServerChangeTracking"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj -c $(buildConfiguration)  
          dotnet pack Projects/Dotmim.Sync.MySql/Dotmim.Sync.MySql.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.MySql  
        displayName: "release nuget Dotmim.Sync.MySql"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.MariaDB/Dotmim.Sync.MariaDB.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.MariaDB/Dotmim.Sync.MariaDB.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.MariaDB  
        displayName: "release nuget Dotmim.Sync.MariaDB"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Sqlite/Dotmim.Sync.Sqlite.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Sqlite  
        displayName: "release nuget Dotmim.Sync.Sqlite"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.PostgreSql/Dotmim.Sync.PostgreSql.csproj -c $(buildConfiguration)
          dotnet pack Projects/Dotmim.Sync.PostgreSql/Dotmim.Sync.PostgreSql.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.PostgreSql
        displayName: "beta nuget Dotmim.Sync.PostgreSql"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Web.Client/Dotmim.Sync.Web.Client.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Web.Client 
        displayName: "release nuget Dotmim.Sync.Web.Client"
        continueOnError: true
      - script: |
          dotnet build Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj -c $(buildConfiguration) 
          dotnet pack Projects/Dotmim.Sync.Web.Server/Dotmim.Sync.Web.Server.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Dotmim.Sync.Web.Server 
        displayName: "release nuget Dotmim.Sync.Web.Server"
        continueOnError: true


    # Publish Build Artifacts
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: $(artifactName)